name: HLS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hls-test-suite:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: "Install LLVM and Clang"
      uses: ./.github/actions/InstallLlvmDependencies
    - name: "Build CIRCT"
      uses: ./.github/actions/BuildCirct

    # --------
    # Compile jlm
    # --------

    - name: Update jlm submodule
      run: git submodule update --init jlm/
    - name: Checkout master of jlm
      run: cd jlm && git checkout master
    - name: Compile jlm
      run: make jlm-release -j `nproc`

    # --------
    # Run HLS test suite
    # --------

    - name: Install verilator
      run: sudo apt-get install verilator
    - name: Run hls-test-suite
      run: make hls-test-run
