name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  polybench:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Update jlm submodule
      run: git submodule update --init jlm/
    - name: Checkout master of jlm
      run: cd jlm && git checkout master
    - name: Compile jlm
      run: make jlm-release -j `nproc`
    - name: Update polybench submodule
      run: git submodule update --init polybench/
    - name: Checkout master of polybench
      run: cd polybench && git checkout master
    - name: Check polybench
      run: make polybench-check -j `nproc`

  llvm-test-suite:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (LLVM)
      run: sudo apt-get update && sudo apt-get install llvm-15-dev clang-15
    - name: Update jlm submodule
      run: git submodule update --init jlm/
    - name: Checkout master of jlm
      run: cd jlm && git checkout master
    - name: Compile jlm
      run: make jlm-release -j `nproc`
    - name: Update llvm-test-suite submodule
      run: git submodule update --init llvm-test-suite/llvm-test-suite.git
    - name: Install lit
      run: make install-lit
    - name: Apply patch
      run: make apply-llvm-git-patch
    - name: Run llvm-test-suite
      run: make llvm-run-opt

  hls-test-suite:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Download prebuilt CIRCT installation
      run: make circt-prebuilt
    - name: Update jlm submodule
      run: git submodule update --init jlm/
    - name: Checkout master of jlm
      run: cd jlm && git checkout master
    - name: Compile jlm
      run: make jlm-release -j `nproc`
    - name: Install verilator
      run: sudo apt-get install verilator
    - name: Run hls-test-suite
      run: make hls-test-run
