name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  polybench:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Get LLVM apt key
      run: wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
    - name: Update apt sources
      run: sudo add-apt-repository deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main

    - name: Install dependencies (LLVM)
      run: sudo apt-get update && sudo apt-get install llvm-16-dev clang-16
    - name: Update jlm submodule
      run: git submodule update --init jlm/
    - name: Checkout master of jlm
      run: cd jlm && git checkout master
    - name: Compile jlm
      run: make jlm-release -j `nproc`
    - name: Update polybench submodule
      run: git submodule update --init polybench/
    - name: Checkout master of polybench
      run: cd polybench && git checkout master
    - name: Check polybench
      run: make polybench-check -j `nproc`

  llvm-test-suite:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Get LLVM apt key
      run: wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
    - name: Update apt sources
      run: sudo add-apt-repository deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main
    - name: Install dependencies (LLVM)
      run: sudo apt-get update && sudo apt-get install llvm-16-dev clang-16
    - name: Update jlm submodule
      run: git submodule update --init jlm/
    - name: Checkout master of jlm
      run: cd jlm && git checkout master
    - name: Compile jlm
      run: make jlm-release -j `nproc`
    - name: Update llvm-test-suite submodule
      run: git submodule update --init llvm-test-suite/llvm-test-suite.git
    - name: Install lit
      run: make install-lit
    - name: Apply patch
      run: make apply-llvm-git-patch
    - name: Run llvm-test-suite
      run: make llvm-run-opt
